### ISSUE TITLE
where can I find the webpack config?

### ISSUE THREAD

**Issue by Alexis374** [insin/react-hn#19]
I am a newbee to learn webpack and react.It seems that you use nwb to wrap the webpack,I want to see the webpack config,where can I find it?

**Comment by insin** [comment]
You might be more interested in react-hn's old webpack config if you;re just getting started: https://github.com/insin/react-hn/tree/v1.4.2

There is no static webpack config in nwb, it creates it on the fly, with various ways of customising it built in. That happens here, starting with the `createWebpackConfig(...)` function: https://github.com/insin/nwb/blob/master/src/createWebpackConfig.js
