### ISSUE TITLE
Upgrade to be a Progressive Web App

### ISSUE THREAD

**Issue by addyosmani** [insin/react-hn#20]
I quite like your HN client implementation :) I was curious if you might be interested in turning it into a [Progressive Web App](https://infrequently.org/2015/06/progressive-apps-escaping-tabs-without-losing-our-soul/) with some offline support using [Service Workers](http://www.html5rocks.com/en/tutorials/service-worker/introduction/).

Some of the specific benefits this would bring include faster first paint/load for subsequent visits and a slightly more pleasant 'add to homescreen' experience for folks using react-hn on mobile (e.g Chrome on Android). The latter can be accomplished using a [Web App Manifest](https://developers.google.com/web/updates/2014/11/Support-for-installable-web-apps-with-webapp-manifest-in-chrome-38-for-Android?hl=en). I'd be happy to PR one in (they look like [this](https://github.com/google/web-starter-kit/blob/master/app/manifest.json)).

There's https://github.com/GoogleChrome/sw-precache for generating a Service Worker of files to precache. I've used this successfully in a bunch of projects. Given you're using WebPack, you could also use [offline-plugin](https://www.npmjs.com/package/offline-plugin) by @nekr to ease some support for SW in. I guess that's something you could try incorporating into https://github.com/insin/nwb/blob/master/src/createWebpackConfig.js if interested via the webpack config object. 

Happy to chat more if interested in the updates needed to make this happen.

**Comment by NekR** [comment]
> I guess that's something you could try incorporating into https://github.com/insin/nwb/blob/master/src/createWebpackConfig.js if interested.

If people here are interested in it, I'll be happy make a PR for it.

**Comment by addyosmani** [comment]
Thanks @nekr! :) Let's see if we can convince @insin these changes are worth bringing in. They'd definitely increase my ability to use this client daily.

**Comment by insin** [comment]
I'd love to make it into a Progressive Web App - it's something I've been meaning to investigate in general for a while now, but my own free time for programming is down to a few hours a week at the moment.

Definitely interesting in a PR for this, and any changes necessary to support it :+1:

**Comment by addyosmani** [comment]
Fantastic :) I started hacking on a prototype of this last night and will try to PR in a piece at a time. 

So far I have caching for a lot of the UI working and you can view story pages you've previously viewed offline.

Comment threads do not yet work offline and I didn't want to try approaching it without checking what you thought first :) Would HNService or the stores be the best place to try layering in caching for comments?

**Comment by NekR** [comment]
I'll be able to make a PR tomorrow (Monday). But not sure what exactly you want to cache in SW. @addyosmani do you cache dynamic pieces from main thread? If so, SW just for app-shell might be enough.

**Comment by addyosmani** [comment]
@NekR I've filed two PRs for a webapp manifest and SW support using sw-precache and sw-toolbox for now. I'd be interested in seeing what SW support using `offline-plugin` would look like (if you have time).

When I tried to get `offline-plugin` working with this project locally, I ran into a few issues:

- Once I'd added the webpack plugin config for it to the project, it was only able to SW cache files that were in the `public/build` directory (files being passed through webpack). This meant that script resources would be in the cache, but not the other resources (index.html/styles/images/etc). 
- Changing the scope of files `offline-plugin` looked at still resulted in it generating sw scripts in the `public/build` directory. This meant that even though it was technically getting the right config, when launched you would get SW scoping errors in devtools saying it couldn't cache files outside of that scope.

My (lack of) knowledge of `offline-plugin`s internals is probably showing, so I just went ahead and used the libraries/build tools I do know how to use for this problem (sw-precache and sw-toolbox). Because they don't need to work directly with webpack is was quick to get those working. Thoughts welcome on the offline-plugin bits!

**Comment by NekR** [comment]
@addyosmani Thanks for detailed info :)

Yes, I'll try to provide `offline-plugin`'s version of SW. 

My plugin is kind of new tool, in compression to `sw-toolbox` or `sw-precache`, so it lacks a lot of important functionalities right now, but I am working on. More people use it, more info I get about what is needed to be done. I am working on a `v3` release at a moment (`v3` branch) which should solve most important issues/features missed in `offline-plugin`.

> Once I'd added the webpack plugin config for it to the project, ...

There is a way to cache `external` assets ('external' relatively to webpack's build output), but it cannot handle CORS requests in a `v2`, `v3` will support it. Also you are using `fastest` network strategy for such resources and I am currently focusing only on `cache-first` strategy. 

> Changing the scope of files offline-plugin looked at still resulted in it  ...

Yeah, it's a bit complicated there. Basically, what you need is a `relativePaths` option, which generates paths to SW relatively to build folder. Also depends on `webpack.config` itself, I didn't looked yet at this project's config, so cannot say for sure what is needed there.

Anyway, I think I still have to do some more work on improving `offline-plugin` to make it ready for more complex PWA than I have at a moment :-) 

Also, if you are interested, here I track progress of `v3`: https://github.com/NekR/offline-plugin/blob/v3/CHANGELOG.md

**Comment by insin** [comment]
I've added you both as collaborators, as I won't be around to merge PRs due to family stuff.

**Comment by addyosmani** [comment]
@insin Completely missed your last comment :) That's awfully kind of you. Thanks for adding us!

**Comment by insin** [comment]
And thanks in kind for using react-hn for this - my time for open source has almost completely disappeared due to emigrating and working nights.

I've mostly been using what time I have for `nwb` as I started using it in a few project s at work. Once I get time to review what it takes to set up a Progressive Web App, I'd like to make it easier to build them using `nwb` by moving as much of the repetitive work and config as possible over to it.

**Comment by insin** [comment]
@addyosmani I should be able to build and release v1.4.11 via [insin.github.com/react-hn](https://github.com/insin/insin.github.com/tree/master/react-hn) when I get home later, or give you collaborator access if you want to do it yourself - your call.

**Comment by addyosmani** [comment]
@insin If you could do a deployment that would be fantastic. I'm also more than happy to push if that's more convenient for you. 

> I've been using what time I have for nwb as I started using it in a few projects at work. Once I get time to review what it takes to set up a Progressive Web App, I'd like to make it easier to build them using nwb by moving as much of the repetitive work and config as possible over to it.

I think that would be very valuable. Tooling for PWAs are still somewhat in their infancy and a lot of folks would benefit from the friction in getting them setup being lowered. Would love to see how `nwb` could help there.

**Comment by addyosmani** [comment]
Another addition to this work over in https://github.com/insin/react-hn/issues/25 now. After this I'd like to see what we can do about support for universal/isomorphic rendering and what perf improvements can be achieved with that path.

**Comment by addyosmani** [comment]
With the latest version now up on the repo, let's close this one and focus on some smaller iterative improvements :)
