### ISSUE TITLE
Links overflow in comments

### ISSUE THREAD

**Issue by NekR** [insin/react-hn#34]
Keep seeing this in comments:

![image](https://cloud.githubusercontent.com/assets/1189265/15093717/9e45e632-1498-11e6-85cc-ccc1cf40d16f.png)

**Comment by addyosmani** [comment]
+1. I think I see two bugs here. One is the layout not adapting to include the full width of the content and the other is link text needing to be truncated a bit (they may well be related to the same issue).

**Comment by felquis** [comment]
I'm sending a PR in a few minutes

**Comment by NekR** [comment]
Fixed in https://github.com/insin/react-hn/pull/42
