### ISSUE TITLE
Update deployed URL in repo to reflect AppEngine hosted version

### ISSUE THREAD

**Issue by addyosmani** [insin/react-hn#38]
The latest version of the app with universal rendering is now up at https://react-hn.appspot.com. I have a few more optimisations locally that I need to PR back in over the coming days, but if we'd like to update the URL in the GitHub 'site'/link field for the repo, please feel free to use it :)

@insin What's the best email address to use if I'd like to add you to the AppEngine instance where this is hosted? I'd be happy to share deployment instructions so you can still update as/when you'd like (it's a 2 liner in the terminal).

**Comment by addyosmani** [comment]
Thanks @insin! :)

**Comment by insin** [comment]
Done - did the same for the README.

Use jonathan.buchanan@gmail.com - having access to redeploy would be great, thanks! Planning to get my Redux on with this and we can switch to React Router's `browserHistory` too now that it has a server.

Thanks for using this app as part of your PWA experimentation - learnt a lot by proxy about a subject I've been meaning to dive into but never found time for :+1:
