### ISSUE TITLE
Layout issue with Settings dialog on iOS

### ISSUE THREAD

**Issue by simevidas** [insin/react-hn#51]
![image](https://cloud.githubusercontent.com/assets/716405/16402694/86d37004-3cee-11e6-999b-4c72d57efd54.png)

**Comment by addyosmani** [comment]
@simevidas Thanks for the bug report. Could you confirm which version of iOS you were testing? I'll get a patch in for this once I know.

**Comment by simevidas** [comment]
iOS 9.3.2, the latest stable version.
