### ISSUE TITLE
Firebase integration

### ISSUE THREAD

**Issue by RichardMaher** [insin/react-hn#52]
Hi,

Looks good!

Can I ask how you integrated with Firebase for "realtime" news updates?

Does your Application Server keep track of all client subscriptions and send and individual news message to each of them or have you been able to utilize FCM's topic broadcast capability?

**Comment by insin** [comment]
Every React component listens to its own corresponding Firebase item using [ReactFire](https://github.com/firebase/reactfire) - I have a post about this aspect of react-hn here:

https://medium.com/@jbscript/lazy-live-data-with-react-79ed1cb1f4d6
