### ISSUE TITLE
[Firefox] Navigation > Comments page is slow to load 

### ISSUE THREAD

**Issue by addyosmani** [insin/react-hn#53]
I haven't been able to repro this in other browsers, but in Firefox (desktop) the top-level Comments page takes a long time to return any data. It works fine with all our other views.

Video: http://recordit.co/uKni7RWp9n
Versions tested: FF 46, 47, 50

Oddly, it works absolutely fine in Firefox for Android (stable).

Similarly odd, testing locally, we have no issues loading this page as quickly as any other in FF50:

<img width="1117" alt="screen shot 2016-06-28 at 13 36 50" src="https://cloud.githubusercontent.com/assets/110953/16415512/8049a41e-3d35-11e6-94af-2854926990b1.png">

Paging @wanderview in case he has more information available that would help with repros.

**Comment by insin** [comment]
Here's Firefox 47 for me using the deployed version:

![2016-06-28_23-32-29](https://cloud.githubusercontent.com/assets/226692/16417336/b4fe72ae-3d88-11e6-9f63-e1170fe3ba41.gif)

**Comment by addyosmani** [comment]
Thanks @insin! I wonder if this issue is resolved for @wanderview now too. Might have been temporary.

**Comment by insin** [comment]
`/newcomments` is sensitive to whatever's happening right now on HN, as it'll keep showing a spinner until somebody creates/updates a comment and its id appears on https://hacker-news.firebaseio.com/v0/updates

**Comment by wanderview** [comment]
The top level comments do work for me with default settings.  Its only when I check "offline mode" do they stop working.  This happens for me across all platform and browser configurations.

Devtools shows this in the console:

HNServiceRest.js:37 Uncaught (in promise) TypeError: l(...).once is not a function(…)

**Comment by wanderview** [comment]
![screenshot 2016-06-28 12 08 43](https://cloud.githubusercontent.com/assets/1256526/16423205/1956f286-3d29-11e6-83f0-a752697edb9b.png)

**Comment by addyosmani** [comment]
@wanderview I can repro this in offline mode now in both FF and Chrome. Marking as a bug and will look into a patch.

**Comment by addyosmani** [comment]
I have a patch locally that I believe fixes this. Deployed to https://react-hn-comments.appspot.com. @wanderview would you mind testing that with Offline Mode enabled please? 🍬

**Comment by wanderview** [comment]
Works great.  Thanks!

**Comment by addyosmani** [comment]
🎉 🎈 🚢 Yay!

Thanks for confirming. I'll get the patch landed soon.
