### ISSUE TITLE
Time-travel new comment highlighting

### ISSUE THREAD

**Issue by insin** [insin/react-hn#62]
Example: https://twitter.com/jbscript/status/778602796497199104

Userscript version for HN proper: https://github.com/insin/greasemonkey/blob/master/hncommenttrees.user.js

This allows you to more easily catch up on threads you were reading on another device.

**Comment by addyosmani** [comment]
That is super nice :)

**Comment by insin** [comment]
![ADHXs0C9lt](https://user-images.githubusercontent.com/226692/82112392-cb96da00-978f-11ea-8000-df05bce6105c.gif)
