### ISSUE TITLE
Offline mode is broken

### ISSUE THREAD

**Issue by denar90** [insin/react-hn#69]
I found out that app isn't working offline. Looks like service-worker was not generated by sw-precahce. It's empty https://github.com/insin/react-hn/blob/master/public/service-worker.js
Probably this [commit](https://github.com/insin/react-hn/commit/2ef88be3cd438c99d39ed8e0cb8679fc94988127#diff-580e737539679088be6cbdf634e8bcceR6) broke it...

**Comment by addyosmani** [comment]
When you say the app isn't working offline: is this testing against https://react-hn.appspot.com/ with Offline Mode switched on in Settings?

**Comment by addyosmani** [comment]
Ah. Confirmed https://react-hn.appspot.com/service-worker.js wasn't generated. I'll rebuild.

**Comment by denar90** [comment]
Yeah. Sorry for bad description.
**Steps to reproduce:**
 - open https://react-hn.appspot.com
 - check offline checkbox  in chrome dev tools in network tab
 - refresh the page

**Comment by addyosmani** [comment]
New deploy is now up. Could you go to DevTools -> Application > Clear Storage -> Clear site storage, refresh and try again? Works here.

**Comment by denar90** [comment]
Now it works fine. Just added better description for people who might face this issue in future.
Thanks.
