### ISSUE TITLE
fresh repo clone fails during postinstall

### ISSUE THREAD

**Issue by nicholas-b-carter** [insin/react-hn#70]
When the `postinstall` script is run, the script fails due to dist dir not existing.

**Comment by nicholas-b-carter** [comment]
@insin

**Comment by derickwarshaw** [comment]
I'm excited to see this implemented.

**Comment by addyosmani** [comment]
Pushed a few fixes that seemed to work for https://github.com/insin/react-hn/issues/72. Can you confirm whether latest master still has issues for you?

**Comment by nicholas-b-carter** [comment]
Can confirm this is fixed now. Thanks!
