### ISSUE TITLE
Error - Not able to do 'npm run build'

### ISSUE THREAD

**Issue by anoopmundathan** [insin/react-hn#72]
#### npm v3.10.9

Getting below error when running ```npm run build``` after cloning the repo and ```npm install```
> ./node_modules/eslint-config-jonnybuchanan/bin/lint.js src

cp: dist/sw-toolbox.js: No such file or directory

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! react-hn@1.6.0 build: `npm run lint && cp node_modules/sw-toolbox/sw-toolbox.js dist/sw-toolbox.js && ./node_modules/.bin/nwb build && npm run copy-manifest && npm run precache`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-hn@1.6.0 build script 'npm run lint && cp node_modules/sw-toolbox/sw-toolbox.js dist/sw-toolbox.js && ./node_modules/.bin/nwb build && npm run copy-manifest && npm run precache'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-hn package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && cp node_modules/sw-toolbox/sw-toolbox.js dist/sw-toolbox.js && ./node_modules/.bin/nwb build && npm run copy-manifest && npm run precache
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-hn
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-hn
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anoopmundathan/projects/web/lab/react-hn/npm-debug.log

### npm-debug-log file
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.10.9
3 info using node@v7.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle react-hn@1.6.0~prebuild: react-hn@1.6.0
6 silly lifecycle react-hn@1.6.0~prebuild: no script for prebuild, continuing
7 info lifecycle react-hn@1.6.0~build: react-hn@1.6.0
8 verbose lifecycle react-hn@1.6.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle react-hn@1.6.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/anoopmundathan/projects/web/lab/react-hn/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/ImageMagick/bin
10 verbose lifecycle react-hn@1.6.0~build: CWD: /Users/anoopmundathan/projects/web/lab/react-hn
11 silly lifecycle react-hn@1.6.0~build: Args: [ '-c',
11 silly lifecycle   'npm run lint && cp node_modules/sw-toolbox/sw-toolbox.js dist/sw-toolbox.js && ./node_modules/.bin/nwb build && npm run copy-manifest && npm run precache' ]
12 silly lifecycle react-hn@1.6.0~build: Returned: code: 1  signal: null
13 info lifecycle react-hn@1.6.0~build: Failed to exec build script
14 verbose stack Error: react-hn@1.6.0 build: `npm run lint && cp node_modules/sw-toolbox/sw-toolbox.js dist/sw-toolbox.js && ./node_modules/.bin/nwb build && npm run copy-manifest && npm run precache`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-hn@1.6.0
16 verbose cwd /Users/anoopmundathan/projects/web/lab/react-hn
17 error Darwin 16.1.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v7.0.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error react-hn@1.6.0 build: `npm run lint && cp node_modules/sw-toolbox/sw-toolbox.js dist/sw-toolbox.js && ./node_modules/.bin/nwb build && npm run copy-manifest && npm run precache`
22 error Exit status 1
23 error Failed at the react-hn@1.6.0 build script 'npm run lint && cp node_modules/sw-toolbox/sw-toolbox.js dist/sw-toolbox.js && ./node_modules/.bin/nwb build && npm run copy-manifest && npm run precache'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-hn package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run lint && cp node_modules/sw-toolbox/sw-toolbox.js dist/sw-toolbox.js && ./node_modules/.bin/nwb build && npm run copy-manifest && npm run precache
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-hn
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-hn
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by addyosmani** [comment]
Recloning master from scratch, I'm able to reproduce this. Looking into what's busted.

**Comment by addyosmani** [comment]
This should be fixed in https://github.com/insin/react-hn/commit/25e5dee8cfdbd0f4c5d84e2037e32a73b4beb3e1. Could you pull the latest changes and try again? This got everything building again locally:

![](https://i.imgur.com/PFeXR9H.jpg)

**Comment by anoopmundathan** [comment]
@addyosmani worked 👍

**Comment by addyosmani** [comment]
Awesome! :)
