### ISSUE TITLE
lighthouse: 'URL responds with a 200 when offline' doesn't pass

### ISSUE THREAD

**Issue by brunoqc** [insin/react-hn#74]
If I run the lighthouse tests, "URL responds with a 200 when offline" doesn't pass.

offline still seems to work.

**Comment by pmachowski** [comment]
Any Ideas why this is happening?

**Comment by addyosmani** [comment]
This appears to have been a bug in Lighthouse. We're all green now:

![screen shot 2017-03-07 at 8 21 06 am](https://cloud.githubusercontent.com/assets/110953/23666624/659fc17e-0310-11e7-812e-75f6186724cd.jpg)

If this is still an issue, feel free to reping and I'll reopen it.
