### ISSUE TITLE
Question: react-router

### ISSUE THREAD

**Issue by eko24ive** [insin/react-hn#80]
I'm just curious why would you decided to use `react-router@2.8.1` not v4 ?
Was this choice made due to some key features which available only for v2 ?

**Comment by tracker1** [comment]
Likely because this project predates v4.

**Comment by eko24ive** [comment]
Whoops, I'm apologize for this one.
GitHub Trending brought me here, so I though this one was fresh repo without looking at the last commit date, sorry 😅
