### ISSUE TITLE
Live link down

### ISSUE THREAD

**Issue by cdurth** [insin/react-hn#99]
Live link appears to have gone dead today (3/20).

Intended?

**Comment by dianjin** [comment]
This was my favorite site to browse HN! I have yet to find another wrapper with collapsible comments.

**Comment by cdurth** [comment]
@dianjin same. I am going to re-deploy it this weekend and will update this with an updated url

**Comment by cdurth** [comment]
https://hn.cdurth.com

**Comment by realPrimoh** [comment]
Just wondering, how did you manage to deploy it?

**Comment by cdurth** [comment]
> 
> 
> Just wondering, how did you manage to deploy it?

I believe all that was necessary was to clone the project and start the node server `npm start`.
I don't recall putting much efforts into getting it running.

**Comment by insin** [comment]
I don't have access to the previous means of deployment - I've switched the main repo branch to the one which is deployed to https://insin.github.io/react-hn
